const raidsList = [
  'Solo CoX',
  'Duo CoX',
  'Trio CoX',
  '4 Man CoX',
  '5 Man CoX',
  'Solo CoX: CM',
  'Duo CoX: CM',
  'Trio CoX: CM',
  '4 Man CoX: CM',
  '5 Man CoX: CM',
  'Solo Theatre of Blood',
  'Duo Theatre of Blood',
  'Trio Theatre of Blood',
  '4 Man Theatre of Blood',
  '5 Man Theatre of Blood',
  'Solo Theatre of Blood: HM',
  'Duo Theatre of Blood: HM',
  'Trio Theatre of Blood: HM',
  '4 Man Theatre of Blood: HM',
  '5 Man Theatre of Blood: HM',
  'Solo TOA',
  'Duo TOA',
  'Trio TOA',
  '4 Man TOA',
  '5 Man TOA',
  '6 Man TOA',
  '7 Man TOA',
  '8 Man TOA',
  'Solo TOA: Expert',
  'Duo TOA: Expert',
  'Trio TOA: Expert',
  '4 Man TOA: Expert',
  '5 Man TOA: Expert',
  '6 Man TOA: Expert',
  '7 Man TOA: Expert',
  '8 Man TOA: Expert',
];

module.exports = raidsList;
